[build]
     command = "cd sis-order-system && vite build --mode production && npx tailwindcss -i ./input.css -o ./dist/output.css --minify"
     publish = "sis-order-system/dist"

   [[redirects]]
     from = "/*"
     to = "/index.html"
     status = 200
