[build]
     command = "npm run build && npx tailwindcss -i ./input.css -o ./dist/output.css --minify"
     publish = "dist"
     environment = {
       VITE_SUPABASE_URL = "https://oyqxerutdwaiqoiabxyy.supabase.co",
       VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95cXhlcnV0ZHdhaXFvaWFieHl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjQ5NTYsImV4cCI6MjA2NzUwMDk1Nn0.RTFFE3fptrpflHJLJ8GnuFr0KphJyIQ2XVakcet8i68"
     }

   [[redirects]]
     from = "/*"
     to = "/index.html"
     status = 200
