[build]
     command = "vite build --mode production && npx tailwindcss -i ./input.css -o ./dist/output.css --minify"
     publish = "dist"

   [[redirects]]
     from = "/*"
     to = "/index.html"
     status = 200
